# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: repeated.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='repeated.proto',
  package='tutorial',
  syntax='proto2',
  serialized_pb=_b('\n\x0erepeated.proto\x12\x08tutorial\"\x16\n\x05Inner\x12\r\n\x05value\x18\x01 \x02(\t\"\'\n\x05Outer\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.tutorial.Inner')
)




_INNER = _descriptor.Descriptor(
  name='Inner',
  full_name='tutorial.Inner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='tutorial.Inner.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=50,
)


_OUTER = _descriptor.Descriptor(
  name='Outer',
  full_name='tutorial.Outer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='tutorial.Outer.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=91,
)

_OUTER.fields_by_name['items'].message_type = _INNER
DESCRIPTOR.message_types_by_name['Inner'] = _INNER
DESCRIPTOR.message_types_by_name['Outer'] = _OUTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inner = _reflection.GeneratedProtocolMessageType('Inner', (_message.Message,), dict(
  DESCRIPTOR = _INNER,
  __module__ = 'repeated_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Inner)
  ))
_sym_db.RegisterMessage(Inner)

Outer = _reflection.GeneratedProtocolMessageType('Outer', (_message.Message,), dict(
  DESCRIPTOR = _OUTER,
  __module__ = 'repeated_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Outer)
  ))
_sym_db.RegisterMessage(Outer)


# @@protoc_insertion_point(module_scope)
