# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: child.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='child.proto',
  package='test',
  syntax='proto2',
  serialized_pb=_b('\n\x0b\x63hild.proto\x12\x04test\"\x07\n\x05\x43hild')
)




_CHILD = _descriptor.Descriptor(
  name='Child',
  full_name='test.Child',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=28,
)

DESCRIPTOR.message_types_by_name['Child'] = _CHILD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Child = _reflection.GeneratedProtocolMessageType('Child', (_message.Message,), dict(
  DESCRIPTOR = _CHILD,
  __module__ = 'child_pb2'
  # @@protoc_insertion_point(class_scope:test.Child)
  ))
_sym_db.RegisterMessage(Child)


# @@protoc_insertion_point(module_scope)
