# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum.proto',
  package='test',
  syntax='proto2',
  serialized_pb=_b('\n\nenum.proto\x12\x04test*(\n\x08Variable\x12\x0e\n\nCONTINUOUS\x10\x00\x12\x0c\n\x08\x44ISCRETE\x10\x01')
)

_VARIABLE = _descriptor.EnumDescriptor(
  name='Variable',
  full_name='test.Variable',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONTINUOUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCRETE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=20,
  serialized_end=60,
)
_sym_db.RegisterEnumDescriptor(_VARIABLE)

Variable = enum_type_wrapper.EnumTypeWrapper(_VARIABLE)
CONTINUOUS = 0
DISCRETE = 1


DESCRIPTOR.enum_types_by_name['Variable'] = _VARIABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
