# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extern.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='extern.proto',
  package='test',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x65xtern.proto\x12\x04test\"K\n\x04\x42ook\x12(\n\tcanonical\x18\x02 \x02(\x0b\x32\x15.test.Book.Identifier\x1a\x19\n\nIdentifier\x12\x0b\n\x03URI\x18\x01 \x02(\t\"9\n\rUserFavourite\x12(\n\tfavourite\x18\x01 \x02(\x0b\x32\x15.test.Book.Identifier')
)




_BOOK_IDENTIFIER = _descriptor.Descriptor(
  name='Identifier',
  full_name='test.Book.Identifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='URI', full_name='test.Book.Identifier.URI', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=97,
)

_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='test.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='canonical', full_name='test.Book.canonical', index=0,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BOOK_IDENTIFIER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=97,
)


_USERFAVOURITE = _descriptor.Descriptor(
  name='UserFavourite',
  full_name='test.UserFavourite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='favourite', full_name='test.UserFavourite.favourite', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=156,
)

_BOOK_IDENTIFIER.containing_type = _BOOK
_BOOK.fields_by_name['canonical'].message_type = _BOOK_IDENTIFIER
_USERFAVOURITE.fields_by_name['favourite'].message_type = _BOOK_IDENTIFIER
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['UserFavourite'] = _USERFAVOURITE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), dict(

  Identifier = _reflection.GeneratedProtocolMessageType('Identifier', (_message.Message,), dict(
    DESCRIPTOR = _BOOK_IDENTIFIER,
    __module__ = 'extern_pb2'
    # @@protoc_insertion_point(class_scope:test.Book.Identifier)
    ))
  ,
  DESCRIPTOR = _BOOK,
  __module__ = 'extern_pb2'
  # @@protoc_insertion_point(class_scope:test.Book)
  ))
_sym_db.RegisterMessage(Book)
_sym_db.RegisterMessage(Book.Identifier)

UserFavourite = _reflection.GeneratedProtocolMessageType('UserFavourite', (_message.Message,), dict(
  DESCRIPTOR = _USERFAVOURITE,
  __module__ = 'extern_pb2'
  # @@protoc_insertion_point(class_scope:test.UserFavourite)
  ))
_sym_db.RegisterMessage(UserFavourite)


# @@protoc_insertion_point(module_scope)
