# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: import.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import child_pb2 as child__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='import.proto',
  package='test',
  syntax='proto2',
  serialized_pb=_b('\n\x0cimport.proto\x12\x04test\x1a\x0b\x63hild.proto\"$\n\x06Parent\x12\x1a\n\x05\x63hild\x18\x01 \x02(\x0b\x32\x0b.test.Child')
  ,
  dependencies=[child__pb2.DESCRIPTOR,])




_PARENT = _descriptor.Descriptor(
  name='Parent',
  full_name='test.Parent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='child', full_name='test.Parent.child', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=71,
)

_PARENT.fields_by_name['child'].message_type = child__pb2._CHILD
DESCRIPTOR.message_types_by_name['Parent'] = _PARENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Parent = _reflection.GeneratedProtocolMessageType('Parent', (_message.Message,), dict(
  DESCRIPTOR = _PARENT,
  __module__ = 'import_pb2'
  # @@protoc_insertion_point(class_scope:test.Parent)
  ))
_sym_db.RegisterMessage(Parent)


# @@protoc_insertion_point(module_scope)
