# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: innerclass.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='innerclass.proto',
  package='test',
  syntax='proto2',
  serialized_pb=_b('\n\x10innerclass.proto\x12\x04test\"J\n\x06Person\x12)\n\rprimary_alias\x18\x02 \x02(\x0b\x32\x12.test.Person.Alias\x1a\x15\n\x05\x41lias\x12\x0c\n\x04name\x18\x01 \x02(\t')
)




_PERSON_ALIAS = _descriptor.Descriptor(
  name='Alias',
  full_name='test.Person.Alias',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='test.Person.Alias.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=100,
)

_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='test.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='primary_alias', full_name='test.Person.primary_alias', index=0,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_ALIAS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=100,
)

_PERSON_ALIAS.containing_type = _PERSON
_PERSON.fields_by_name['primary_alias'].message_type = _PERSON_ALIAS
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(

  Alias = _reflection.GeneratedProtocolMessageType('Alias', (_message.Message,), dict(
    DESCRIPTOR = _PERSON_ALIAS,
    __module__ = 'innerclass_pb2'
    # @@protoc_insertion_point(class_scope:test.Person.Alias)
    ))
  ,
  DESCRIPTOR = _PERSON,
  __module__ = 'innerclass_pb2'
  # @@protoc_insertion_point(class_scope:test.Person)
  ))
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.Alias)


# @@protoc_insertion_point(module_scope)
