# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: innerclass_dict.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='innerclass_dict.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15innerclass_dict.proto\x12\x04test\"[\n\nOuterClass\x12(\n\x04\x65num\x18\x02 \x01(\x0e\x32\x1a.test.OuterClass.InnerEnum\"#\n\tInnerEnum\x12\n\n\x06\x45NUM_1\x10\x00\x12\n\n\x06\x45NUM_2\x10\x01\x62\x06proto3'
)



_OUTERCLASS_INNERENUM = _descriptor.EnumDescriptor(
  name='InnerEnum',
  full_name='test.OuterClass.InnerEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ENUM_1', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENUM_2', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=87,
  serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_OUTERCLASS_INNERENUM)


_OUTERCLASS = _descriptor.Descriptor(
  name='OuterClass',
  full_name='test.OuterClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enum', full_name='test.OuterClass.enum', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OUTERCLASS_INNERENUM,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=122,
)

_OUTERCLASS.fields_by_name['enum'].enum_type = _OUTERCLASS_INNERENUM
_OUTERCLASS_INNERENUM.containing_type = _OUTERCLASS
DESCRIPTOR.message_types_by_name['OuterClass'] = _OUTERCLASS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OuterClass = _reflection.GeneratedProtocolMessageType('OuterClass', (_message.Message,), {
  'DESCRIPTOR' : _OUTERCLASS,
  '__module__' : 'innerclass_dict_pb2'
  # @@protoc_insertion_point(class_scope:test.OuterClass)
  })
_sym_db.RegisterMessage(OuterClass)


# @@protoc_insertion_point(module_scope)
