# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutual.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mutual.proto',
  package='test',
  syntax='proto2',
  serialized_pb=_b('\n\x0cmutual.proto\x12\x04test\"\x1e\n\x01\x41\x12\x19\n\x08\x62_mutual\x18\x01 \x02(\x0b\x32\x07.test.B\"\x1e\n\x01\x42\x12\x19\n\x08\x61_mutual\x18\x01 \x02(\x0b\x32\x07.test.A')
)




_A = _descriptor.Descriptor(
  name='A',
  full_name='test.A',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b_mutual', full_name='test.A.b_mutual', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_B = _descriptor.Descriptor(
  name='B',
  full_name='test.B',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a_mutual', full_name='test.B.a_mutual', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=84,
)

_A.fields_by_name['b_mutual'].message_type = _B
_B.fields_by_name['a_mutual'].message_type = _A
DESCRIPTOR.message_types_by_name['A'] = _A
DESCRIPTOR.message_types_by_name['B'] = _B
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

A = _reflection.GeneratedProtocolMessageType('A', (_message.Message,), dict(
  DESCRIPTOR = _A,
  __module__ = 'mutual_pb2'
  # @@protoc_insertion_point(class_scope:test.A)
  ))
_sym_db.RegisterMessage(A)

B = _reflection.GeneratedProtocolMessageType('B', (_message.Message,), dict(
  DESCRIPTOR = _B,
  __module__ = 'mutual_pb2'
  # @@protoc_insertion_point(class_scope:test.B)
  ))
_sym_db.RegisterMessage(B)


# @@protoc_insertion_point(module_scope)
